-- 004 · Learn: courses, lessons, entitlements, progress, flashcards, quizzes.
--
-- Courses are digital content and therefore in-app purchase only (Apple
-- §3.1.1). No course price is ever charged through an external checkout, and the
-- server holds no course price at all — the store is the pricing authority.

CREATE TYPE department AS ENUM (
  'orthodontics',
  'digital',
  'business_paradental'
);

CREATE TABLE courses (
  id                integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug              text NOT NULL UNIQUE,
  title_en          text NOT NULL,
  title_ar          text NOT NULL,
  subtitle_en       text NOT NULL DEFAULT '',
  subtitle_ar       text NOT NULL DEFAULT '',
  description_en    text NOT NULL DEFAULT '',
  description_ar    text NOT NULL DEFAULT '',
  department        department NOT NULL,
  level_en          text NOT NULL DEFAULT '',
  level_ar          text NOT NULL DEFAULT '',
  cpd_points        integer NOT NULL DEFAULT 0,
  instructor_name_en text NOT NULL DEFAULT '',
  instructor_name_ar text NOT NULL DEFAULT '',
  instructor_bio_en text NOT NULL DEFAULT '',
  instructor_bio_ar text NOT NULL DEFAULT '',
  -- The store product identifier. Deliberately no price column.
  iap_product_id    text NOT NULL,
  thumbnail_url     text,
  is_published      boolean NOT NULL DEFAULT true,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX courses_department_idx ON courses (department) WHERE is_published;

CREATE TABLE lessons (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_id        integer NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
  position         integer NOT NULL,
  title_en         text NOT NULL,
  title_ar         text NOT NULL,
  duration_seconds integer NOT NULL DEFAULT 0,
  video_url        text,
  -- Lesson one is always a free preview, in every course.
  is_free_preview  boolean NOT NULL DEFAULT false,
  UNIQUE (course_id, position)
);

CREATE TABLE handouts (
  id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_id   integer NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
  title_en    text NOT NULL,
  title_ar    text NOT NULL,
  storage_key text NOT NULL,
  bytes       bigint NOT NULL DEFAULT 0,
  mime_type   text NOT NULL DEFAULT 'application/pdf'
);

-- What a user owns. Written only by a verified store receipt or an admin grant;
-- never by a client assertion.
CREATE TABLE entitlements (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  course_id    integer NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
  source       text NOT NULL CHECK (source IN ('iap', 'admin_grant', 'dev')),
  -- Store transaction id. Unique so a replayed receipt cannot grant twice.
  external_ref text,
  granted_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, course_id)
);

CREATE UNIQUE INDEX entitlements_external_ref_unique
  ON entitlements (external_ref)
  WHERE external_ref IS NOT NULL;

CREATE TABLE enrollments (
  user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  course_id    integer NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
  started_at   timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  PRIMARY KEY (user_id, course_id)
);

-- Playback position survives backgrounding, app restart and reinstall, because
-- it lives here rather than in client state.
CREATE TABLE lesson_progress (
  user_id          uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  lesson_id        integer NOT NULL REFERENCES lessons (id) ON DELETE CASCADE,
  position_seconds integer NOT NULL DEFAULT 0 CHECK (position_seconds >= 0),
  is_complete      boolean NOT NULL DEFAULT false,
  completed_at     timestamptz,
  updated_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, lesson_id)
);

CREATE TABLE flashcard_decks (
  id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_id integer REFERENCES courses (id) ON DELETE CASCADE,
  title_en  text NOT NULL,
  title_ar  text NOT NULL
);

CREATE TABLE flashcards (
  id       integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  deck_id  integer NOT NULL REFERENCES flashcard_decks (id) ON DELETE CASCADE,
  position integer NOT NULL,
  front_en text NOT NULL,
  front_ar text NOT NULL,
  back_en  text NOT NULL,
  back_ar  text NOT NULL,
  UNIQUE (deck_id, position)
);

-- Per-user spacing state. Deterministic scheduling, never a random "mastery"
-- percentage (brief §38).
CREATE TABLE flashcard_states (
  user_id       uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  flashcard_id  integer NOT NULL REFERENCES flashcards (id) ON DELETE CASCADE,
  interval_days integer NOT NULL DEFAULT 0,
  repetitions   integer NOT NULL DEFAULT 0,
  ease          numeric(4, 2) NOT NULL DEFAULT 2.50,
  due_on        date NOT NULL DEFAULT CURRENT_DATE,
  updated_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, flashcard_id)
);

CREATE INDEX flashcard_states_due_idx ON flashcard_states (user_id, due_on);

-- Every review is kept, so a session summary reports what happened rather than
-- what the client remembers.
CREATE TABLE flashcard_reviews (
  id           bigserial PRIMARY KEY,
  user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  flashcard_id integer NOT NULL REFERENCES flashcards (id) ON DELETE CASCADE,
  outcome      text NOT NULL CHECK (outcome IN ('again', 'got_it')),
  reviewed_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX flashcard_reviews_user_idx ON flashcard_reviews (user_id, reviewed_at DESC);

CREATE TABLE quizzes (
  id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_id integer NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
  title_en  text NOT NULL,
  title_ar  text NOT NULL,
  pass_mark integer NOT NULL DEFAULT 60
);

CREATE TABLE quiz_questions (
  id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  quiz_id        integer NOT NULL REFERENCES quizzes (id) ON DELETE CASCADE,
  position       integer NOT NULL,
  prompt_en      text NOT NULL,
  prompt_ar      text NOT NULL,
  explanation_en text NOT NULL DEFAULT '',
  explanation_ar text NOT NULL DEFAULT '',
  UNIQUE (quiz_id, position)
);

CREATE TABLE quiz_options (
  id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  question_id integer NOT NULL REFERENCES quiz_questions (id) ON DELETE CASCADE,
  position    integer NOT NULL,
  label_en    text NOT NULL,
  label_ar    text NOT NULL,
  -- The answer key never leaves the server until an attempt is graded.
  is_correct  boolean NOT NULL DEFAULT false,
  UNIQUE (question_id, position)
);

CREATE TABLE quiz_attempts (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  quiz_id       integer NOT NULL REFERENCES quizzes (id) ON DELETE CASCADE,
  score_percent integer NOT NULL CHECK (score_percent BETWEEN 0 AND 100),
  correct_count integer NOT NULL,
  question_count integer NOT NULL,
  submitted_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX quiz_attempts_user_idx ON quiz_attempts (user_id, quiz_id, submitted_at DESC);

CREATE TABLE quiz_answers (
  attempt_id  uuid NOT NULL REFERENCES quiz_attempts (id) ON DELETE CASCADE,
  question_id integer NOT NULL REFERENCES quiz_questions (id) ON DELETE CASCADE,
  option_id   integer REFERENCES quiz_options (id) ON DELETE SET NULL,
  is_correct  boolean NOT NULL,
  PRIMARY KEY (attempt_id, question_id)
);

CREATE TABLE course_downloads (
  user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  lesson_id    integer NOT NULL REFERENCES lessons (id) ON DELETE CASCADE,
  bytes        bigint NOT NULL DEFAULT 0,
  downloaded_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, lesson_id)
);
