-- 005 · People: professionals, availability, holds, bookings, earnings.
--
-- Sessions are human services, so they are paid through an external checkout
-- (70/30 split) — never through in-app purchase. That is the opposite rule from
-- courses, and the inconsistency is legal, not accidental. Never harmonise them.

CREATE TYPE service_kind AS ENUM ('tutoring', 'mentoring', 'consulting');

CREATE TYPE credential_evidence AS ENUM ('verified', 'stated');

CREATE TYPE booking_status AS ENUM (
  'pending_payment',
  'confirmed',
  'completed',
  'cancelled_by_student',
  'cancelled_by_professional',
  'payment_failed'
);

CREATE TABLE professionals (
  id                     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id                uuid REFERENCES users (id) ON DELETE SET NULL,
  slug                   text NOT NULL UNIQUE,
  kind                   service_kind NOT NULL,
  display_name_en        text NOT NULL,
  display_name_ar        text NOT NULL,
  headline_en            text NOT NULL DEFAULT '',
  headline_ar            text NOT NULL DEFAULT '',
  bio_en                 text NOT NULL DEFAULT '',
  bio_ar                 text NOT NULL DEFAULT '',
  specialties            text[] NOT NULL DEFAULT '{}',
  languages              text[] NOT NULL DEFAULT '{}',
  -- Server-authoritative. A price arriving from a client is never trusted.
  hourly_rate_egp        integer NOT NULL CHECK (hourly_rate_egp > 0),
  -- 15 minutes, where the professional enables it.
  offers_free_intro_call boolean NOT NULL DEFAULT false,
  -- A mentor is someone who made the move; the card leads with the journey.
  journey_from           text,
  journey_to             text,
  journey_year           integer,
  timezone               text NOT NULL DEFAULT 'Africa/Cairo',
  cancellation_policy_en text NOT NULL DEFAULT '',
  cancellation_policy_ar text NOT NULL DEFAULT '',
  avatar_url             text,
  is_approved            boolean NOT NULL DEFAULT false,
  approved_at            timestamptz,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX professionals_kind_idx ON professionals (kind) WHERE is_approved;
CREATE INDEX professionals_journey_idx ON professionals (journey_to) WHERE is_approved;

CREATE TABLE professional_qualifications (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  professional_id integer NOT NULL REFERENCES professionals (id) ON DELETE CASCADE,
  position        integer NOT NULL,
  title_en        text NOT NULL,
  title_ar        text NOT NULL,
  issuer_en       text NOT NULL DEFAULT '',
  issuer_ar       text NOT NULL DEFAULT '',
  -- Verified by Ejadah versus stated by the tutor. Never conflated.
  evidence        credential_evidence NOT NULL DEFAULT 'stated',
  year            integer,
  document_key    text,
  UNIQUE (professional_id, position)
);

CREATE TABLE professional_packages (
  id                 integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  professional_id    integer NOT NULL REFERENCES professionals (id) ON DELETE CASCADE,
  title_en           text NOT NULL,
  title_ar           text NOT NULL,
  session_count      integer NOT NULL CHECK (session_count > 0),
  session_minutes    integer NOT NULL CHECK (session_minutes > 0),
  price_egp          integer NOT NULL CHECK (price_egp > 0),
  cadence_sentence_en text NOT NULL DEFAULT '',
  cadence_sentence_ar text NOT NULL DEFAULT '',
  is_active          boolean NOT NULL DEFAULT true
);

-- Recurring weekly availability. 0 = Sunday, matching the booking calendar,
-- which starts on Sunday in both languages.
CREATE TABLE availability_rules (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  professional_id integer NOT NULL REFERENCES professionals (id) ON DELETE CASCADE,
  weekday         smallint NOT NULL CHECK (weekday BETWEEN 0 AND 6),
  start_minute    integer NOT NULL CHECK (start_minute BETWEEN 0 AND 1439),
  end_minute      integer NOT NULL CHECK (end_minute BETWEEN 1 AND 1440),
  CONSTRAINT availability_rules_ordered CHECK (end_minute > start_minute)
);

CREATE INDEX availability_rules_professional_idx
  ON availability_rules (professional_id, weekday);

-- One-off blocks or extra hours that override the weekly rules.
CREATE TABLE availability_exceptions (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  professional_id integer NOT NULL REFERENCES professionals (id) ON DELETE CASCADE,
  period          tstzrange NOT NULL,
  is_available    boolean NOT NULL DEFAULT false,
  reason          text
);

CREATE INDEX availability_exceptions_idx
  ON availability_exceptions USING gist (professional_id, period);

CREATE TABLE bookings (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  professional_id   integer NOT NULL REFERENCES professionals (id) ON DELETE RESTRICT,
  package_id        integer REFERENCES professional_packages (id) ON DELETE SET NULL,
  kind              service_kind NOT NULL,
  status            booking_status NOT NULL DEFAULT 'pending_payment',
  -- Calculated and validated on the server from the professional's own rate or
  -- package price. The client never determines an authoritative price.
  total_egp         integer NOT NULL CHECK (total_egp >= 0),
  platform_fee_egp  integer NOT NULL DEFAULT 0 CHECK (platform_fee_egp >= 0),
  subject           text NOT NULL DEFAULT '',
  -- Free text the student writes. Never sent to analytics, never logged.
  goal              text NOT NULL DEFAULT '',
  cancelled_at      timestamptz,
  refunded_egp      integer,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX bookings_user_idx ON bookings (user_id, created_at DESC);
CREATE INDEX bookings_professional_idx ON bookings (professional_id, created_at DESC);

-- Every scheduled session has its own real time. An eight-session package is
-- eight rows, never one vague appointment object (brief §53).
CREATE TABLE booking_sessions (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id  uuid NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
  position    integer NOT NULL,
  starts_at   timestamptz NOT NULL,
  ends_at     timestamptz NOT NULL,
  attended_at timestamptz,
  UNIQUE (booking_id, position),
  CONSTRAINT booking_sessions_ordered CHECK (ends_at > starts_at)
);

CREATE INDEX booking_sessions_time_idx ON booking_sessions (starts_at);

-- THE concurrency guarantee.
--
-- A professional's timeline lives in exactly one table so that a single
-- exclusion constraint can span both temporary holds and confirmed sessions.
-- Two transactions racing for the same slot cannot both commit: PostgreSQL
-- rejects the second with a constraint violation, which the API turns into the
-- 409 "someone booked that time a moment ago" state. The application never
-- relies on read-then-write checks, and it certainly never relies on Flutter.
CREATE TABLE slot_reservations (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  professional_id    integer NOT NULL REFERENCES professionals (id) ON DELETE CASCADE,
  period             tstzrange NOT NULL,
  kind               text NOT NULL CHECK (kind IN ('hold', 'session')),
  -- 'active' rows occupy the timeline; 'released' rows are history.
  status             text NOT NULL DEFAULT 'active'
                       CHECK (status IN ('active', 'released')),
  -- Holds only. Server-controlled duration; expiry is enforced by a background
  -- job and re-checked inside every booking transaction.
  expires_at         timestamptz,
  held_by_user_id    uuid REFERENCES users (id) ON DELETE CASCADE,
  booking_id         uuid REFERENCES bookings (id) ON DELETE CASCADE,
  booking_session_id uuid REFERENCES booking_sessions (id) ON DELETE CASCADE,
  created_at         timestamptz NOT NULL DEFAULT now(),
  released_at        timestamptz,
  CONSTRAINT slot_reservations_hold_has_expiry
    CHECK (kind <> 'hold' OR expires_at IS NOT NULL),
  CONSTRAINT slot_reservations_session_has_booking
    CHECK (kind <> 'session' OR booking_id IS NOT NULL),
  CONSTRAINT slot_reservations_no_overlap
    EXCLUDE USING gist (
      professional_id WITH =,
      period WITH &&
    ) WHERE (status = 'active')
);

CREATE INDEX slot_reservations_expiry_idx
  ON slot_reservations (expires_at)
  WHERE kind = 'hold' AND status = 'active';

CREATE INDEX slot_reservations_professional_idx
  ON slot_reservations USING gist (professional_id, period)
  WHERE status = 'active';

CREATE TABLE reviews (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id      uuid NOT NULL UNIQUE REFERENCES bookings (id) ON DELETE CASCADE,
  user_id         uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  professional_id integer NOT NULL REFERENCES professionals (id) ON DELETE CASCADE,
  rating          smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
  body            text NOT NULL DEFAULT '',
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX reviews_professional_idx ON reviews (professional_id, created_at DESC);

-- Six-step tutor application, saved as a draft at every step.
CREATE TABLE tutor_applications (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
  status        professional_status NOT NULL DEFAULT 'draft',
  last_step     integer NOT NULL DEFAULT 1 CHECK (last_step BETWEEN 1 AND 6),
  payload       jsonb NOT NULL DEFAULT '{}'::jsonb,
  submitted_at  timestamptz,
  reviewed_at   timestamptz,
  reviewer_id   uuid REFERENCES users (id) ON DELETE SET NULL,
  rejection_reason text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- Three checkable actions given on approval; progress persists on the dashboard.
CREATE TABLE playbook_progress (
  user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  item         text NOT NULL,
  completed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, item)
);

-- gross − fee = net, itemised. A tutor should never be surprised by the deal.
CREATE TABLE earnings (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  professional_id  integer NOT NULL REFERENCES professionals (id) ON DELETE CASCADE,
  booking_id       uuid NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
  gross_egp        integer NOT NULL,
  platform_fee_egp integer NOT NULL,
  status           text NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending', 'available', 'paid', 'reversed')),
  occurred_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (booking_id)
);

CREATE INDEX earnings_professional_idx ON earnings (professional_id, occurred_at DESC);

CREATE TABLE payout_requests (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  professional_id integer NOT NULL REFERENCES professionals (id) ON DELETE CASCADE,
  amount_egp      integer NOT NULL CHECK (amount_egp > 0),
  status          text NOT NULL DEFAULT 'requested'
                    CHECK (status IN ('requested', 'approved', 'paid', 'rejected')),
  requested_at    timestamptz NOT NULL DEFAULT now(),
  resolved_at     timestamptz,
  resolver_id     uuid REFERENCES users (id) ON DELETE SET NULL
);
