// ─── Shared pricing plan data ─────────────────────────────────────────────────

export type PlanId = "student-pass" | "exam-pro" | "cpd-premium" | "career-pro" | "ai-pro" | "elite";

export interface PlanFeature {
  label: string;
  included: boolean | string; // true = ✓, false = ✗, string = limited/note
}

export interface Plan {
  id: PlanId;
  name: string;
  tagline: string;
  monthlyEGP?: number;
  annualEGP?: number;
  monthlyUSD?: number;
  annualUSD?: number;
  currency: "EGP" | "USD";
  color: string;
  badge?: string;
  forWho: string;
  forWhoDetail: string;
  emoji: string;
  highlights: string[];
  features: Record<string, boolean | string>;
  testimonial?: { name: string; role: string; quote: string };
  faq: { q: string; a: string }[];
}

export const FEATURE_GROUPS: Record<string, string[]> = {
  "Learning": [
    "Courses access",
    "Course video lessons",
    "Course handouts & PDFs",
    "Flashcards",
    "Quizzes",
    "Live Academy sessions",
    "Clinical Demos",
    "Dental Library",
  ],
  "Exams": [
    "Free practice tests",
    "Full EDLE question bank (14,200+)",
    "Mock exams",
    "Exam analytics",
    "EDLE subject breakdown",
    "International exam prep (ORE, DHA, ADC)",
  ],
  "Career & Masters": [
    "Career Abroad country guides",
    "Masters Database access",
    "King's MSc full profile",
    "Program comparison tool",
    "Career roadmap builder",
    "1-on-1 consulting session (free/month)",
  ],
  "AI & Tools": [
    "Dental AI (basic)",
    "Dental AI (unlimited)",
    "Course AI assistant",
    "EDLE AI revision coach",
    "Research Hub access",
  ],
  "Community & Profile": [
    "Community access",
    "NFC digital profile",
    "Achievements & badges",
    "Certificate center",
    "Priority support",
  ],
  "Services": [
    "Tutoring marketplace access",
    "1 free tutoring session/month",
    "Mentoring marketplace access",
    "Consulting marketplace access",
    "Group sessions discount",
  ],
};

export const PLANS: Plan[] = [
  {
    id: "student-pass",
    name: "Student Pass",
    tagline: "Everything a dental student needs to pass and progress",
    monthlyEGP: 299,
    annualEGP: 2690,
    currency: "EGP",
    color: "#2D9B68",
    forWho: "Dental students — Years 1 through Internship",
    forWhoDetail: "If you're in dental school and need strong foundations, structured revision tools, and a community that understands your curriculum — this is your plan.",
    emoji: "🎓",
    badge: undefined,
    highlights: [
      "Full course library — all specialties",
      "Flashcards, quizzes, and handouts for every course",
      "Community access — ask seniors and specialists",
      "Basic Dental AI for quick clinical questions",
      "Certificate center — earn verified completion certificates",
    ],
    features: {
      "Courses access": true,
      "Course video lessons": true,
      "Course handouts & PDFs": true,
      "Flashcards": true,
      "Quizzes": true,
      "Live Academy sessions": "5/month",
      "Clinical Demos": true,
      "Dental Library": true,
      "Free practice tests": true,
      "Full EDLE question bank (14,200+)": false,
      "Mock exams": false,
      "Exam analytics": false,
      "EDLE subject breakdown": false,
      "International exam prep (ORE, DHA, ADC)": false,
      "Career Abroad country guides": "Basic",
      "Masters Database access": "Basic",
      "King's MSc full profile": false,
      "Program comparison tool": false,
      "Career roadmap builder": false,
      "1-on-1 consulting session (free/month)": false,
      "Dental AI (basic)": true,
      "Dental AI (unlimited)": false,
      "Course AI assistant": false,
      "EDLE AI revision coach": false,
      "Research Hub access": true,
      "Community access": true,
      "NFC digital profile": true,
      "Achievements & badges": true,
      "Certificate center": true,
      "Priority support": false,
      "Tutoring marketplace access": true,
      "1 free tutoring session/month": false,
      "Mentoring marketplace access": false,
      "Consulting marketplace access": false,
      "Group sessions discount": "10%",
    },
    testimonial: {
      name: "Rana M., Year 4",
      role: "Cairo University Dental School",
      quote: "The flashcards and quizzes saved my Oral Biology exam. I was failing the department practicals and after 3 weeks on Ejadah I passed with distinction.",
    },
    faq: [
      { q: "Can I cancel anytime?", a: "Yes — Student Pass is monthly with no lock-in. Cancel before your next billing date and you won't be charged again." },
      { q: "Does this include EDLE preparation?", a: "Student Pass includes free practice tests only. For the full 14,200-question bank and mock exams, you need Exam Pro." },
      { q: "Can I switch to another plan later?", a: "Yes — upgrade anytime. We prorate the cost so you only pay the difference for the remaining days in your billing cycle." },
    ],
  },
  {
    id: "exam-pro",
    name: "Exam Pro",
    tagline: "Pass the EDLE and every licensing exam — first attempt",
    monthlyEGP: 499,
    annualEGP: 4490,
    currency: "EGP",
    color: "#FF6B1A",
    badge: "Most Popular",
    forWho: "Final-year students and recent graduates preparing for EDLE",
    forWhoDetail: "You're done with university and the EDLE is your next gate. You need the full question bank, timed mocks, performance analytics, and a coach that tracks your weak subjects. This is that plan.",
    emoji: "📝",
    highlights: [
      "Full EDLE question bank — 14,200+ questions across all 16 subjects",
      "Unlimited mock exams with real exam conditions",
      "Exam analytics — track weak subjects, improvement trends, predicted score",
      "EDLE AI revision coach — asks you questions, explains wrong answers",
      "Everything in Student Pass included",
    ],
    features: {
      "Courses access": true,
      "Course video lessons": true,
      "Course handouts & PDFs": true,
      "Flashcards": true,
      "Quizzes": true,
      "Live Academy sessions": "10/month",
      "Clinical Demos": true,
      "Dental Library": true,
      "Free practice tests": true,
      "Full EDLE question bank (14,200+)": true,
      "Mock exams": "Unlimited",
      "Exam analytics": true,
      "EDLE subject breakdown": true,
      "International exam prep (ORE, DHA, ADC)": false,
      "Career Abroad country guides": "Basic",
      "Masters Database access": "Basic",
      "King's MSc full profile": false,
      "Program comparison tool": false,
      "Career roadmap builder": false,
      "1-on-1 consulting session (free/month)": false,
      "Dental AI (basic)": true,
      "Dental AI (unlimited)": false,
      "Course AI assistant": true,
      "EDLE AI revision coach": true,
      "Research Hub access": true,
      "Community access": true,
      "NFC digital profile": true,
      "Achievements & badges": true,
      "Certificate center": true,
      "Priority support": false,
      "Tutoring marketplace access": true,
      "1 free tutoring session/month": false,
      "Mentoring marketplace access": false,
      "Consulting marketplace access": false,
      "Group sessions discount": "15%",
    },
    testimonial: {
      name: "Dr. Khaled N.",
      role: "Passed EDLE — Class of 2025",
      quote: "I failed the EDLE once before finding Ejadah. The analytics showed I was weak in Pharmacology and Pathology. 6 weeks of targeted practice and I passed with 82%. The mock exams are identical in difficulty to the real thing.",
    },
    faq: [
      { q: "How realistic are the mock exams?", a: "Our question bank is compiled from EDLE past papers, validated by dentists who sat the exam in 2023–2025. The format, difficulty distribution, and subject weighting match the actual exam." },
      { q: "Does this include international exam prep (ORE, DHA)?", a: "No — international licensing exam prep is included in CPD Premium and above. Exam Pro focuses on the EDLE specifically." },
      { q: "What happens to my mock exam scores after I pass?", a: "Your exam history stays on your profile permanently. You can export it as a PDF showing your preparation journey — useful for applications." },
    ],
  },
  {
    id: "cpd-premium",
    name: "CPD Premium",
    tagline: "Continuous development for practising Egyptian dentists",
    monthlyEGP: 799,
    annualEGP: 7190,
    currency: "EGP",
    color: "#8B5CF6",
    forWho: "Practising dentists who want to grow clinically and plan ahead",
    forWhoDetail: "You're licensed, practising, and serious about staying current — CPD hours, international exam preparation, clinical skills, and the tools to plan a career move when the time comes.",
    emoji: "🔬",
    highlights: [
      "Everything in Exam Pro",
      "Unlimited Live Academy sessions + Clinical Demos",
      "International exam prep — ORE (UK), DHA/DOH (UAE), ADC (Australia), NDEB (Canada)",
      "Full Career Abroad guides — all 23 countries with interactive checklists",
      "Full Masters Database access with program comparison",
    ],
    features: {
      "Courses access": true,
      "Course video lessons": true,
      "Course handouts & PDFs": true,
      "Flashcards": true,
      "Quizzes": true,
      "Live Academy sessions": "Unlimited",
      "Clinical Demos": true,
      "Dental Library": true,
      "Free practice tests": true,
      "Full EDLE question bank (14,200+)": true,
      "Mock exams": "Unlimited",
      "Exam analytics": true,
      "EDLE subject breakdown": true,
      "International exam prep (ORE, DHA, ADC)": true,
      "Career Abroad country guides": "Full",
      "Masters Database access": "Full",
      "King's MSc full profile": true,
      "Program comparison tool": true,
      "Career roadmap builder": true,
      "1-on-1 consulting session (free/month)": false,
      "Dental AI (basic)": true,
      "Dental AI (unlimited)": true,
      "Course AI assistant": true,
      "EDLE AI revision coach": true,
      "Research Hub access": true,
      "Community access": true,
      "NFC digital profile": true,
      "Achievements & badges": true,
      "Certificate center": true,
      "Priority support": false,
      "Tutoring marketplace access": true,
      "1 free tutoring session/month": false,
      "Mentoring marketplace access": true,
      "Consulting marketplace access": true,
      "Group sessions discount": "20%",
    },
    testimonial: {
      name: "Dr. Mariam S.",
      role: "General Dentist, Alexandria",
      quote: "The ORE preparation materials and the UK career guide are worth the subscription alone. I passed Part 1 ORE on my first attempt after 4 months of preparation on Ejadah while working full time.",
    },
    faq: [
      { q: "Does CPD Premium give me CPD certificates?", a: "Yes — all completed courses and live sessions generate verifiable CPD certificates through Ejadah's accreditation system, accepted by the Egyptian Dental Syndicate." },
      { q: "Can I access the Masters Database filtering fully?", a: "Yes — CPD Premium gives full database access including Best-for-Me quiz, cost estimator, compare tray, and all scholarship information." },
      { q: "Is the Career Abroad section complete at this tier?", a: "Yes — all 23 countries with full interactive checklists, salary data, document guides, and the degree recognition checker." },
    ],
  },
  {
    id: "career-pro",
    name: "Career Pro",
    tagline: "Built for dentists who are ready to move internationally",
    monthlyUSD: 29,
    annualUSD: 249,
    currency: "USD",
    color: "#496FA8",
    forWho: "Dentists actively planning a career move abroad",
    forWhoDetail: "You've made the decision to move. Now you need a real plan, expert guidance, and the tools to execute it. Career Pro is a premium-tier plan priced in USD because it's built for international ambitions.",
    emoji: "✈️",
    highlights: [
      "Everything in CPD Premium",
      "1 free 30-min consulting session per month (Career or Masters advice)",
      "Priority access to new country guides and pathway updates",
      "Unlimited Dental AI — ask anything about licensing, recognition, visa",
      "Career roadmap builder with personalised milestone tracking",
    ],
    features: {
      "Courses access": true,
      "Course video lessons": true,
      "Course handouts & PDFs": true,
      "Flashcards": true,
      "Quizzes": true,
      "Live Academy sessions": "Unlimited",
      "Clinical Demos": true,
      "Dental Library": true,
      "Free practice tests": true,
      "Full EDLE question bank (14,200+)": true,
      "Mock exams": "Unlimited",
      "Exam analytics": true,
      "EDLE subject breakdown": true,
      "International exam prep (ORE, DHA, ADC)": true,
      "Career Abroad country guides": "Full + Priority updates",
      "Masters Database access": "Full",
      "King's MSc full profile": true,
      "Program comparison tool": true,
      "Career roadmap builder": "Personalised",
      "1-on-1 consulting session (free/month)": "1 session/month",
      "Dental AI (basic)": true,
      "Dental AI (unlimited)": true,
      "Course AI assistant": true,
      "EDLE AI revision coach": true,
      "Research Hub access": true,
      "Community access": true,
      "NFC digital profile": true,
      "Achievements & badges": true,
      "Certificate center": true,
      "Priority support": true,
      "Tutoring marketplace access": true,
      "1 free tutoring session/month": false,
      "Mentoring marketplace access": true,
      "Consulting marketplace access": true,
      "Group sessions discount": "20%",
    },
    testimonial: {
      name: "Dr. Amr F.",
      role: "Now practising in Dubai Healthcare City",
      quote: "The free monthly consulting session is what made the difference. My consultant told me exactly which documents DHA needed and in what order. I had my specialist licence in 11 weeks. Worth every dollar.",
    },
    faq: [
      { q: "Does the free consulting session roll over if I don't use it?", a: "No — it's 1 session per calendar month, use it or lose it. We recommend scheduling it on the 1st of every month to build a structured plan." },
      { q: "Why is this plan priced in USD?", a: "Career Pro is designed for dentists planning international careers, who will be earning in USD, GBP, AED, or AUD. Pricing in USD reflects the international scope of what's included." },
      { q: "Can I use the consulting session for Masters application advice?", a: "Yes — consulting sessions can cover career migration, Masters applications, personal statement review, or any professional advisory need." },
    ],
  },
  {
    id: "ai-pro",
    name: "AI Pro",
    tagline: "Unlimited AI — clinical answers, revision, research, all day",
    monthlyUSD: 19,
    annualUSD: 169,
    currency: "USD",
    color: "#FF2D32",
    forWho: "Any dentist who wants the full power of Dental AI with no limits",
    forWhoDetail: "You use Dental AI constantly for clinical references, drug interactions, exam revision, and research. AI Pro removes all limits and adds specialised AI tools — EDLE revision coach, Course AI on every course, and a research summariser.",
    emoji: "🧠",
    highlights: [
      "Unlimited Dental AI — no daily message caps",
      "EDLE AI revision coach — quiz mode, instant explanations, weak-spot tracking",
      "Course AI on every course — ask questions about specific lesson content",
      "AI research summariser — paste any paper, get a clinical summary in 30 seconds",
      "Priority AI response time",
    ],
    features: {
      "Courses access": true,
      "Course video lessons": true,
      "Course handouts & PDFs": true,
      "Flashcards": true,
      "Quizzes": true,
      "Live Academy sessions": "5/month",
      "Clinical Demos": true,
      "Dental Library": true,
      "Free practice tests": true,
      "Full EDLE question bank (14,200+)": false,
      "Mock exams": false,
      "Exam analytics": false,
      "EDLE subject breakdown": false,
      "International exam prep (ORE, DHA, ADC)": false,
      "Career Abroad country guides": "Basic",
      "Masters Database access": "Basic",
      "King's MSc full profile": true,
      "Program comparison tool": false,
      "Career roadmap builder": false,
      "1-on-1 consulting session (free/month)": false,
      "Dental AI (basic)": true,
      "Dental AI (unlimited)": true,
      "Course AI assistant": true,
      "EDLE AI revision coach": true,
      "Research Hub access": true,
      "Community access": true,
      "NFC digital profile": true,
      "Achievements & badges": true,
      "Certificate center": true,
      "Priority support": false,
      "Tutoring marketplace access": true,
      "1 free tutoring session/month": false,
      "Mentoring marketplace access": false,
      "Consulting marketplace access": false,
      "Group sessions discount": "10%",
    },
    testimonial: {
      name: "Dr. Dina K.",
      role: "Resident, Oral Surgery",
      quote: "I use Dental AI between every patient. Drug interactions, dosing, case review — it's like having a reference library that talks back. The EDLE revision coach helped me help my junior colleagues too.",
    },
    faq: [
      { q: "What's the difference between basic and unlimited Dental AI?", a: "Basic Dental AI has a cap of 20 messages per day. Unlimited removes all caps, adds priority response speed, and unlocks the specialised revision coach and research summariser modes." },
      { q: "Can I combine AI Pro with another plan?", a: "AI Pro can be added as a standalone plan or its AI features are included in Career Pro and Elite. If you want both exam prep and unlimited AI, Exam Pro + AI Pro gives you both — or just go Elite for everything." },
      { q: "Does the AI have access to the latest dental research?", a: "Dental AI is updated quarterly with new clinical guidelines, drug updates, and emerging evidence. It cites its sources so you can always verify the original reference." },
    ],
  },
  {
    id: "elite",
    name: "Elite",
    tagline: "The complete Ejadah experience — nothing held back",
    monthlyUSD: 99,
    annualUSD: 899,
    currency: "USD",
    color: "#FFC62E",
    badge: "Best Value",
    forWho: "Serious professionals who want everything Ejadah offers",
    forWhoDetail: "Elite is for the dentist who refuses to leave anything on the table. Every feature, every tool, every service — plus a free tutoring session every month, priority support, and the NFC Elite card.",
    emoji: "👑",
    highlights: [
      "Every feature from every other plan — nothing excluded",
      "1 free 60-min tutoring session per month (any specialty)",
      "1 free 30-min consulting session per month",
      "Priority support — dedicated response within 4 hours",
      "Elite NFC card — black anodised aluminium, laser-engraved",
      "Early access to new features and beta tools",
    ],
    features: {
      "Courses access": true,
      "Course video lessons": true,
      "Course handouts & PDFs": true,
      "Flashcards": true,
      "Quizzes": true,
      "Live Academy sessions": "Unlimited",
      "Clinical Demos": true,
      "Dental Library": true,
      "Free practice tests": true,
      "Full EDLE question bank (14,200+)": true,
      "Mock exams": "Unlimited",
      "Exam analytics": true,
      "EDLE subject breakdown": true,
      "International exam prep (ORE, DHA, ADC)": true,
      "Career Abroad country guides": "Full + Priority",
      "Masters Database access": "Full",
      "King's MSc full profile": true,
      "Program comparison tool": true,
      "Career roadmap builder": "Personalised",
      "1-on-1 consulting session (free/month)": "1 session/month",
      "Dental AI (basic)": true,
      "Dental AI (unlimited)": true,
      "Course AI assistant": true,
      "EDLE AI revision coach": true,
      "Research Hub access": true,
      "Community access": true,
      "NFC digital profile": true,
      "Achievements & badges": true,
      "Certificate center": true,
      "Priority support": "4-hour response",
      "Tutoring marketplace access": true,
      "1 free tutoring session/month": "60-min session",
      "Mentoring marketplace access": true,
      "Consulting marketplace access": true,
      "Group sessions discount": "25%",
    },
    testimonial: {
      name: "Dr. Karim S.",
      role: "Endodontist, Riyadh",
      quote: "I've been an Elite member since the beginning. The free tutoring session alone covers half the cost — I use it to coach my younger colleagues. The priority support is real; I had a billing issue resolved in 90 minutes.",
    },
    faq: [
      { q: "Do the free sessions (tutoring + consulting) stack if unused?", a: "No — sessions are 1 per calendar month, non-rolling. Schedule them early in the month." },
      { q: "What is the Elite NFC card?", a: "A physical black anodised aluminium card with your name, specialty, and QR code laser-engraved. Tap it to any phone and your Ejadah profile opens instantly. Ships to Egypt within 2–3 weeks of subscription activation." },
      { q: "Is there a discount for Egyptian hospitals or universities buying multiple Elite seats?", a: "Yes — institutional pricing is available for 5+ seats. Contact consulting@ejadah.com for a quote." },
    ],
  },
];

export function getPlan(id: string): Plan | undefined {
  return PLANS.find((p) => p.id === id);
}

export function formatPrice(plan: Plan, annual: boolean): string {
  if (plan.currency === "EGP") {
    const price = annual ? Math.round((plan.annualEGP ?? 0) / 12) : (plan.monthlyEGP ?? 0);
    return `EGP ${price.toLocaleString()}`;
  }
  const price = annual ? Math.round((plan.annualUSD ?? 0) / 12) : (plan.monthlyUSD ?? 0);
  return `$${price}`;
}

export function annualSaving(plan: Plan): string {
  if (plan.currency === "EGP") {
    const monthlyTotal = (plan.monthlyEGP ?? 0) * 12;
    const annual = plan.annualEGP ?? 0;
    const pct = Math.round(((monthlyTotal - annual) / monthlyTotal) * 100);
    return `${pct}%`;
  }
  const monthlyTotal = (plan.monthlyUSD ?? 0) * 12;
  const annual = plan.annualUSD ?? 0;
  const pct = Math.round(((monthlyTotal - annual) / monthlyTotal) * 100);
  return `${pct}%`;
}
