import 'package:ejadah_mobile/features/profile/presentation/widgets/qr_matrix.dart';
import 'package:flutter_test/flutter_test.dart';

/// The QR encoder, checked against a reference implementation.
///
/// A QR code that does not scan is the same class of defect as a broken image:
/// it looks right until a stranger points a phone at a printed card, which is
/// the one moment the growth loop depends on. So this suite does not test that
/// "a pattern is drawn" — it compares the produced matrix, module for module,
/// against vectors generated by the `qrcode` reference encoder at error
/// correction level L, byte mode, for every mask and every version the app can
/// produce.
void main() {
  group('encoding matches the reference encoder', () {
    for (final entry in _payloads.entries) {
      for (var mask = 0; mask < 8; mask++) {
        test('${entry.key}, mask $mask', () {
          final matrix = QrMatrix.encodeWithMask(entry.value, mask);
          expect(matrix, isNotNull, reason: 'payload must fit versions 1-5');

          final expected = _reference['${entry.key}|$mask']!;
          expect(matrix!.version, expected.version);
          expect(_digest(_flatten(matrix)), expected.digest);
        });
      }
    }
  });

  test('the version grows with the payload, and stops at 5', () {
    // Twelve header bits then eight per byte, so each version holds two
    // fewer bytes than it has data codewords.
    expect(QrMatrix.encode('x' * 17)!.version, 1);
    expect(QrMatrix.encode('x' * 18)!.version, 2);
    expect(QrMatrix.encode('x' * 32)!.version, 2);
    expect(QrMatrix.encode('x' * 33)!.version, 3);
    expect(QrMatrix.encode('x' * 53)!.version, 3);
    expect(QrMatrix.encode('x' * 54)!.version, 4);
    expect(QrMatrix.encode('x' * 78)!.version, 4);
    expect(QrMatrix.encode('x' * 79)!.version, 5);
    expect(QrMatrix.encode('x' * QrMatrix.maxBytes)!.version, 5);
    // Beyond the supported range the encoder says so rather than producing a
    // truncated code; the card screen then shows the link as text.
    expect(QrMatrix.encode('x' * (QrMatrix.maxBytes + 1)), isNull);
    expect(QrMatrix.encode(''), isNull);
  });

  test('a real card URL produces a version-3 code', () {
    final matrix = QrMatrix.encode(
      'https://ejadah.international/dr/nour-hassan',
    )!;
    expect(matrix.version, 3);
    expect(matrix.size, 29);
    expect(matrix.mask, inInclusiveRange(0, 7));
  });

  test('the anchor matrix is drawn exactly', () {
    // A full matrix written out, so a failure is readable rather than a
    // changed hash. Generated by the reference encoder for "A", mask 0.
    final matrix = QrMatrix.encodeWithMask('A', 0)!;
    final rows = [
      for (var y = 0; y < matrix.size; y++)
        [
          for (var x = 0; x < matrix.size; x++) matrix.isDark(x, y) ? '#' : '.',
        ].join(),
    ];
    expect(rows, _anchor);
  });

  test('the function patterns are where the specification puts them', () {
    final matrix = QrMatrix.encode(
      'https://ejadah.international/verify/EJ-DEMO-0001',
    )!;
    final size = matrix.size;

    // The three finder centres are dark, and their separators are light.
    for (final centre in [(3, 3), (size - 4, 3), (3, size - 4)]) {
      expect(matrix.isDark(centre.$1, centre.$2), isTrue);
      // The light ring two modules out from the centre.
      expect(matrix.isDark(centre.$1 + 2, centre.$2), isFalse);
      // And the dark ring beyond it.
      expect(matrix.isDark(centre.$1 - 3, centre.$2), isTrue);
    }

    // The timing patterns alternate.
    for (var i = 8; i < size - 8; i++) {
      expect(matrix.isDark(6, i), i.isEven, reason: 'timing column at $i');
      expect(matrix.isDark(i, 6), i.isEven, reason: 'timing row at $i');
    }

    // The module that is always dark.
    expect(matrix.isDark(8, size - 8), isTrue);
  });

  test('the data codewords carry the payload in byte mode', () {
    final codewords = QrMatrix.debugCodewords('A')!;
    // 0x40 = byte mode, 0x14 0x10 = length 1 then 'A' (0x41) straddling the
    // nibble boundary, then the specified alternating pad bytes.
    expect(codewords.take(3), [0x40, 0x14, 0x10]);
    expect(codewords.skip(3).take(4), [0xEC, 0x11, 0xEC, 0x11]);
    // 19 data codewords plus 7 error-correction codewords at version 1 level L.
    expect(codewords, hasLength(26));
  });
}

const Map<String, String> _payloads = {
  'short': 'A',
  'card': 'https://ejadah.international/dr/nour-hassan',
  'verify': 'https://ejadah.international/verify/EJ-DEMO-0001',
  'longHandle':
      'https://ejadah.international/dr/'
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'longCode':
      'https://ejadah.international/verify/'
      'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ',
};

typedef _Vector = ({int version, String digest});

/// FNV-1a digests of the reference matrices, flattened row-major as `0`/`1`.
const Map<String, _Vector> _reference = {
  'short|0': (version: 1, digest: 'd72b7fe738bcbd41'),
  'short|1': (version: 1, digest: 'cf754ead1d9a5ce7'),
  'short|2': (version: 1, digest: 'fb1fea922c9f6283'),
  'short|3': (version: 1, digest: 'bd73529388e01a89'),
  'short|4': (version: 1, digest: 'c890995be6152ae3'),
  'short|5': (version: 1, digest: 'f39b7c466b9020e5'),
  'short|6': (version: 1, digest: 'b1e1674b1df64675'),
  'short|7': (version: 1, digest: 'ac5efa94bc414a13'),
  'card|0': (version: 3, digest: '146f3656c151654b'),
  'card|1': (version: 3, digest: 'cb16708dd4ec3615'),
  'card|2': (version: 3, digest: '3e7f9e6cd1f19278'),
  'card|3': (version: 3, digest: '75a95d08332f1ec3'),
  'card|4': (version: 3, digest: '42bbb518860ecd30'),
  'card|5': (version: 3, digest: 'ddd71e8dac2b01e0'),
  'card|6': (version: 3, digest: 'b008f775a6b47d93'),
  'card|7': (version: 3, digest: '392ae473a8f6a271'),
  'verify|0': (version: 3, digest: 'de1add1fb8a18d57'),
  'verify|1': (version: 3, digest: '0ca75d6796fe81cd'),
  'verify|2': (version: 3, digest: '603407eac2888420'),
  'verify|3': (version: 3, digest: '21dfd59372e2253b'),
  'verify|4': (version: 3, digest: '8c449be76a05cf58'),
  'verify|5': (version: 3, digest: 'a551a506733fd068'),
  'verify|6': (version: 3, digest: '7c94c373d413d5f3'),
  'verify|7': (version: 3, digest: '7dd873769ceb985d'),
  'longHandle|0': (version: 4, digest: 'fc6ece9602386e91'),
  'longHandle|1': (version: 4, digest: '7152bb09e7e4692f'),
  'longHandle|2': (version: 4, digest: '39b1a4dd0a8c9786'),
  'longHandle|3': (version: 4, digest: '4fc959722d65b246'),
  'longHandle|4': (version: 4, digest: '7f4bdbce070dbf7f'),
  'longHandle|5': (version: 4, digest: '148726dd3619de59'),
  'longHandle|6': (version: 4, digest: '5bc57157c879fc2a'),
  'longHandle|7': (version: 4, digest: 'cee1a4c6226d86e8'),
  'longCode|0': (version: 4, digest: '647937a8eec787a7'),
  'longCode|1': (version: 4, digest: 'fa44cdce155b728d'),
  'longCode|2': (version: 4, digest: '54332f2dbd374324'),
  'longCode|3': (version: 4, digest: '3ddd279b693afbe4'),
  'longCode|4': (version: 4, digest: '73013330202b39d5'),
  'longCode|5': (version: 4, digest: 'bf30c34bb4682e5f'),
  'longCode|6': (version: 4, digest: 'f470a297a8a5c498'),
  'longCode|7': (version: 4, digest: '54e182e4a996d76a'),
};

/// The reference matrix for "A" at mask 0, written out in full.
const List<String> _anchor = [
  '#######..#.##.#######',
  '#.....#..###..#.....#',
  '#.###.#.##.##.#.###.#',
  '#.###.#..#.#..#.###.#',
  '#.###.#...#.#.#.###.#',
  '#.....#.....#.#.....#',
  '#######.#.#.#.#######',
  '........##.##........',
  '###.########.##...#..',
  '#.##....#.....#...##.',
  '.#.####..##.#...#...#',
  '.#.##...##....#...#..',
  '..##.##.#...#.#.#.#.#',
  '........#..#.#.#.#.#.',
  '#######.#.##.###.####',
  '#.....#.######.###...',
  '#.###.#.##.#.###.##.#',
  '#.###.#..##...#...##.',
  '#.###.#.##..#...#...#',
  '#.....#.#.....#...##.',
  '#######.###.#.#.#.###',
];

String _flatten(QrMatrix matrix) {
  final buffer = StringBuffer();
  for (var y = 0; y < matrix.size; y++) {
    for (var x = 0; x < matrix.size; x++) {
      buffer.write(matrix.isDark(x, y) ? '1' : '0');
    }
  }
  return buffer.toString();
}

/// FNV-1a, 64-bit. Chosen so the vectors above stay short and so the test
/// needs no dependency to verify them.
String _digest(String value) {
  var hash = BigInt.parse('cbf29ce484222325', radix: 16);
  final prime = BigInt.parse('100000001b3', radix: 16);
  final mask = (BigInt.one << 64) - BigInt.one;
  for (final unit in value.codeUnits) {
    hash = (hash ^ BigInt.from(unit)) * prime & mask;
  }
  return hash.toRadixString(16).padLeft(16, '0');
}
